Fix formatting of Kotlin source and XMLs
android/gradle-recipes pull request #33
Opened 2022-08-15 01:12 UTC by codekarma

- Fixed formatting of Kotlin source file through ktfmt
- Fixed indentations in manifest xmls
- Fixed a readme of addManifestPlaceholderFromTask

2023-12-07 17:19 UTC, Angie20182 approved these changes
# []()

2023-12-08 00:29 UTC, TWiStErRob requested changes
Overall I like the idea, but I strongly disagree with the end result. I think it's neither Google style, nor production-ready enterprise style.

(I know it's not really production code, but since these are "recipes" people will copy the code AND style.)

2023-12-08 00:29 UTC, TWiStErRob commented on BuildSrc/customizeAgpDsl/app/build.gradle.kts
> +    buildTypes { debug { the<BuildTypeExtension>().invocationParameters = "-debug -log" } }
Is this preventable? This is not good style, official examples should not suggest this is good practice, we're not golfing, but trying to write maintainable and easy to understand Gradle code, right?

Same with one-liner `plugins { ... }`.

2023-12-08 00:29 UTC, TWiStErRob commented on BuildSrc/customizeAgpDsl/app/src/main/AndroidManifest.xml
> +</manifest>
if fixing formatting:
```suggestion
</manifest>

```

2023-12-08 00:29 UTC, TWiStErRob commented on BuildSrc/customizeAgpDslAndVariant/buildSrc/src/main/kotlin/ExampleTask.kt
> +    @get:Input abstract val parameters: Property<String>
This is also golfing.

2023-12-08 00:29 UTC, TWiStErRob commented on BuildSrc/manifestReplacementTest/buildSrc/src/main/kotlin/VerifyManifestTask.kt
> +        if (builtArtifacts.elements.size != 1) throw RuntimeException("Expected one APK !")
can the formatter auto-add braces instead of single-lining it?
```suggestion
        if (builtArtifacts.elements.size != 1) {
            throw RuntimeException("Expected one APK !")
        }
```

2023-12-08 03:25 UTC, ducrohet commented
Thanks for this pull request (and sorry for having ignored it for a long time). At this time, we cannot accept contributions to the 7.x branch. Our mechanism for these branches is quite problematic. The source of truth is in our internal server, organized in a very different way than what is published on github.

The good news is that for 8.x and beyond we have a new process that will allow us to take contributions. You can already look at the studio-main branch and make contribution there. Note that the recipe are not usable as-is there, and we have a tool to help. I'm actually in the process of cleaning this up a bit and documenting it better. Please take a look again next week.

With this setup we'll be able to update all agp-* branches (for AGP 8.x+)

2023-12-08 03:26 UTC, closed without merging